name: Node.js CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'

    - name: Print current directory
      run: pwd
      working-directory: ./Y76Backend

    - name: Print contents of the Y76Backend directory
      run: ls -al
      working-directory: ./Y76Backend

    - name: Print npm config
      run: npm config list
      working-directory: ./Y76Backend

    - name: Debugging - Check for package-lock.json explicitly
      run: if [ -f package-lock.json ]; then echo "package-lock.json exists"; else echo "package-lock.json does not exist"; fi
      working-directory: ./Y76Backend

