name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci
      working-directory: ./Y76Backend

    - name: Run build
      run: npm run build --if-present
      working-directory: ./Y76Backend

    - name: Run tests
      run: npm test
      working-directory: ./Y76Backend

    - name: Deploy to Production
      if: github.ref == 'refs/heads/main'
      run: ./deploy.sh
      env:
        NODE_ENV: production
      working-directory: ./Y76Backend
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_SERVER: ${{ secrets.DB_SERVER }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        HASHED_PASSWORD: ${{ secrets.HASHED_PASSWORD }}
