name: Node.js CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: List files
      run: ls -la ./Y76Backend
      working-directory: .

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      working-directory: ./Y76Backend

    - name: Run build
      run: npm run build
      working-directory: ./Y76Backend

    - name: Run tests
      run: npm test
      working-directory: ./Y76Backend

    - name: Deploy to Production
      run: ./deploy.sh
      working-directory: ./Y76Backend
      env:
        NODE_ENV: production
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_SERVER: ${{ secrets.DB_SERVER }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        HASHED_PASSWORD: ${{ secrets.HASHED_PASSWORD }}
