name: Node.js CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]  # Updated Node.js versions

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3  # Updated to v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci
      working-directory: ./Y76Backend

    - name: Run build
      run: npm run build --if-present
      working-directory: ./Y76Backend

    - name: Run tests
      run: npm test
      working-directory: ./Y76Backend

    - name: Deploy to Production
      if: github.ref == 'refs/heads/master'
      run: ./deploy.sh
      working-directory: ./Y76Backend
      env:
        NODE_ENV: production
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_SERVER: ${{ secrets.DB_SERVER }}
        DB_DATABASE: ${{ secrets.DB_DATABASE }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        HASHED_PASSWORD: ${{ secrets.HASHED_PASSWORD }}
